version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=PeriferiaSocial
      - POSTGRES_USER=PeriferiaSocial
      - POSTGRES_PASSWORD=PeriferiaSocialPass
    ports:
      - '2345:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql